name: ritnet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::cudatoolkit=11.3
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - tqdm
  - joblib
  - visdom
  - jsonpatch
  - pip
  - pip:
    - torchsummary
    - opencv-python==4.1.1.26
