


# basic_with_zero_out

# Training parameters

# More situationally changed parameters
path_to_data: "./Data/vein_and_sclera_data"
batch_size: 2
learning_rate: 0.00001
num_of_dataloader_workers: 7
train_epoch_size_limit: 400

# More trainig-type-defining parameters
num_epochs_per_training_iteration: 1
cleanup_k: 3      # Options: 0, 1, 2, 3
optimizer_used: "Adam"    # Options: Adam, SGD, LBFGS
zero_out_non_sclera_on_predictions: True
loss_fn_name: "JACCARD"
alphas: []

# Dataset parameters
dataset_option: "aug_tf"    # Options: aug_old
zero_out_non_sclera: True
add_sclera_to_img: False
add_bcosfire_to_img: True
add_coye_to_img: True

# Model parameters that need to be set in stone for pruning
model_type: res_att
model: "64_1_6"
input_width: 128
input_height: 128
input_channels: 5
output_channels: 2



# Pruning parameters

# more situationally changed parameters
num_train_iters_between_prunings: 10
max_auto_prunings: 70
proportion_to_prune: 0.01

# More pruning-type-defining parameters
prune_by_original_percent: True
num_filters_to_prune: -1 # not applied
prune_n_kernels_at_once: 100
resource_name_to_prune_by: "flops_num"        # Options: flops_num, weights_num, kernels_num
importance_func: IPAD_eq        # Options: [0.5, 0.5, 0.5], 0, 1

